language: php

php:
 - 5.5
 - 5.4
 - 5.3

env:
 - LARAVEL_ENV=travis

before_script:
 - mysql -e 'create database vocab_laravel;'
 - cd www
 - composer self-update
 - composer install --dev
 - php artisan migrate --env=travis
 - php artisan db:seed --env=travis
 - php artisan env

after_script:
 - php artisan migrate:reset --env=travis
 - php artisan cache:clear
 - composer clear

script: phpunit