language: php

php:
 - 5.5
 - 5.4
 - 5.3

before_script:
 - mysql -e 'create database vocab_laravel;'
 - cd www
 - composer self-update
 - composer install --dev
 - php artisan migrate
 - php artisan db:seed

script: phpunit