<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-22 at 16:33:22.
 * @author rellek
 */
class VocabTest extends PHPUnit_Framework_TestCase {
    /**
     * @var Vocab
     */
    protected $vocabId;
    
    /**
     * @var Vocab
     */
    protected $vocabNoId;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        require_once '../src/Vocab.php';
        $this->vocabNoId = new Vocab(
                "test word", "noun", array("Testwort", "Beispiel"));
        $this->vocabId = new Vocab(
                "test word", "noun", array("Testwort", "Beispiel"), 1);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Vocab::getId
     * @expectedException PHPUnit_Framework_Error_Warning
     */
    public function testGetIdNoId() {
        $this->vocabNoId->getId(); // throws error since no id was set.
    }

    /**
     * @covers Vocab::getId
     */
    public function testGetIdId() {
        $this->assertEquals(
                $this->vocabId->getId(), 1);
    }

    /**
     * @covers Vocab::getWord
     */
    public function testGetWord() {
        $this->assertEquals(
                $this->vocabNoId->getWord(), "test word");
    }

    /**
     * @covers Vocab::getType
     */
    public function testGetType() {
        $this->assertEquals(
                $this->vocabNoId->getType(), "noun");
    }

    /**
     * @covers Vocab::getTranslations
     */
    public function testGetTranslations() {
        $this->assertEquals(
                $this->vocabId->getTranslations(), array("Testwort", "Beispiel")
        );
    }

}
