<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-22 at 16:52:34.
 */
class VocabDbAccessTest extends PHPUnit_Framework_TestCase {

    /**
     * @var VocabDbAccess
     */
    protected $dbHandler;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        require_once '../../src/VocabDbAccess.php';
        $this->dbHandler = new VocabDbAccess();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        $totalInsertions = 2;
        $query = 'DELETE FROM vocab ORDER BY vid DESC LIMIT 1';
        for($i = 0; $i < $totalInsertions; $i++) {
            mysqli_query($this->dbHandler->getDbHandle(), $query);
        }
    }


    /**
     * @covers VocabDbAccess::insertVocab
     */
    public function testInsertVocab() {
        require_once '../../src/Vocab.php';
        $vocab = new Vocab("hard","adjective",array("hart", "anstrengend", "nervtötend"));
        $this->assertTrue($this->dbHandler->insertVocab(array($vocab)));
        
        // now we know, that the db is not empty. (max index +=1)
        $vocab2 = new Vocab("easy","adjective",array("leicht", "einfach", "leichtfällig"));
        
        $queryResult = mysqli_fetch_assoc(mysqli_query(
                $this->dbHandler->getDbHandle(), 'SELECT MAX(vid) FROM vocab'));
        $maxIndexBefore = $queryResult['MAX(vid)'];
        $this->dbHandler->insertVocab(array($vocab2));
        $queryResult2 = mysqli_fetch_assoc(mysqli_query(
                $this->dbHandler->getDbHandle(), 'SELECT MAX(vid) FROM vocab'));
        $maxIndexAfter = $queryResult2['MAX(vid)'];
        // test correct indexing in db.
        $this->assertGreaterThan($maxIndexBefore, $maxIndexAfter);
        $this->assertEquals($maxIndexBefore + 1, $maxIndexAfter);
    }

}
